version: '3.2'

services:
    my_django_service:
      build: .
      stdin_open: true
      tty: true
      ports:
        - "8000:8000"
      working_dir: /app
      command: python3 manage.py runserver 0.0.0.0:8000
      volumes:
        - ../my_project/my_project:/app
      environment:
        - "PYTHONUNBUFFERED=1"
      expose:
        - "8000"
